### PR TITLE
[Improvements] 

### PR DESCRIPTION
**Pull request by eshanized**
### Changes and description:

1. First it will check for `sudo` privileges.
2. Backup existing `makepkg` config before changing the flags
3. Main function has some modification with error handling
4. in case any failure, it will restore original `makepkg` config

### CODE REVIEW

**Comment by arcolinuxz** [comment]
do changes in the -DEV githubs

**Comment by eshanized** [comment]
sure sir, I am sorry

**Comment by arcolinuxz** [comment]
you can stop now
some things will not be logged

**Comment by eshanized** [comment]
Okay sir❤️

**Comment by arcolinuxz** [comment]
next time better check with me whether I want things to be changed and always in the -Dev or -nemesis githubs

**Comment by eshanized** [comment]
Okay sir

**Pull request merged**
